---
# - notify: Stop mesos-slave
#   when: run_mode == 'Stop'

# - notify: Stop mesos-master
#   when: run_mode == 'Stop'

- include: install.yml
  when: run_mode == 'Deploy' or run_mode == 'Install'

- include: configure.yml
  when: run_mode == 'Deploy' or run_mode == 'Configure'
