---

- name: Install all dev system tools
  sudo: yes
  apt:
    name='{{item}}'
    state=installed
    update_cache=yes
    cache_valid_time=3600
    force=yes
  with_items:
    - 'zookeeperd'

- name: Copy zookeeper config
  sudo: yes
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg mode=0644
  notify:
    - restart zookeeper

- name: Copy zookeeper id
  sudo: yes
  template: src=myid.j2 dest=/etc/zookeeper/conf/myid mode=0644
  notify:
    - restart zookeeper

- name: Add zookeeper cleanup to cron
  sudo: yes
  cron: name="zookeeper cleanup" weekday="*" minute=0 hour=3
        user="root" job="/usr/share/zookeeper/bin/zkCleanup.sh"
        cron_file=ansible_zookeper

- name: Start zookeeper service
  sudo: yes
  service: name=zookeeper state=started

